[package]
name = "oxmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
kuchikiki = "0.8.2"
ratatui = "0.26.1"
reqwest = { version = "0.11.24", features = ["blocking"] }
